// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGP02DoiWCua-bthnS3bmovL9mQXK7ckY',
    appId: '1:661158397537:web:0068064fc7b3fa182acc20',
    messagingSenderId: '661158397537',
    projectId: 'usedev-projeto',
    authDomain: 'usedev-projeto.firebaseapp.com',
    storageBucket: 'usedev-projeto.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJCjLClRHXtt5OoosRK2tw0Id26bQXgmE',
    appId: '1:661158397537:android:f61e6c7e7fc060f82acc20',
    messagingSenderId: '661158397537',
    projectId: 'usedev-projeto',
    storageBucket: 'usedev-projeto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOD9t2K0O86DWjt6jreZiabnDOYezHDVk',
    appId: '1:661158397537:ios:815061d19622f80c2acc20',
    messagingSenderId: '661158397537',
    projectId: 'usedev-projeto',
    storageBucket: 'usedev-projeto.firebasestorage.app',
    iosBundleId: 'com.example.projetoUsedev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOD9t2K0O86DWjt6jreZiabnDOYezHDVk',
    appId: '1:661158397537:ios:815061d19622f80c2acc20',
    messagingSenderId: '661158397537',
    projectId: 'usedev-projeto',
    storageBucket: 'usedev-projeto.firebasestorage.app',
    iosBundleId: 'com.example.projetoUsedev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGP02DoiWCua-bthnS3bmovL9mQXK7ckY',
    appId: '1:661158397537:web:b518b331f12bafc12acc20',
    messagingSenderId: '661158397537',
    projectId: 'usedev-projeto',
    authDomain: 'usedev-projeto.firebaseapp.com',
    storageBucket: 'usedev-projeto.firebasestorage.app',
  );
}
